pipeline:
  test:
    image: androidbuildsdk27:latest
    commands:
      - bash ./gradlew build assemble -PdisablePreDex
  build:
    image: androidbuildsdk27:latest
    commands:
      - bash ./gradlew test assemble -PdisablePreDex
